apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: gitopsdemo-dev
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - image: quay.io/keycloak/keycloak:latest
        args: ["start-dev"]
        name: keycloak
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: kind-terraform-learn-pguser-kind-terraform-learn, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: kind-terraform-learn-pguser-kind-terraform-learn, key: port } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: kind-terraform-learn-pguser-kind-terraform-learn, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: kind-terraform-learn-pguser-kind-terraform-learn, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: kind-terraform-learn-pguser-kind-terraform-learn, key: password } }
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
      restartPolicy: Always
